"""Added image_url column to Post

Revision ID: 83577accf072
Revises: 652f3a0881df
Create Date: 2024-12-01 15:11:22.793572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83577accf072'
down_revision = '652f3a0881df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('media_url')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
