"""Initial migration

Revision ID: 846bf165dea2
Revises: 96a0e85f5ca6
Create Date: 2024-12-04 20:50:39.078385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846bf165dea2'
down_revision = '96a0e85f5ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
